gantt
    title Issuing Multi-Region - 2024/2025 plan
    dateFormat YYYY-Q
    axisFormat %Y-Q%q
    tickInterval 3month
    todayMarker off
    section Global <br>Milestones
        MILESTONE - PRODUCT AND TECHNICAL DISCOVERIES COMPLETE: crit, milestone, 2025-1, m1
        MILESTONE - DEVELOPMENT AND TESTING COMPLETE (no EGW): crit, milestone, 2025-4, m2
        MILESTONE - CLIENT GO-LIVE: crit, milestone, 2025-6, m3
    section CMS
        Remove HSM dependency for virtual card creation (1FTE):cmsd1, 2025-1, 14d
        Remove HSM dependency for virtual card generate/verify credentials (1FTE):cmsd2, after cmsd1, 14d
        Development and testing: after cmsd2, 60d
        Product and technical discoveries: 2024-8, 140d
    section CMS SRE
        SRE Discoveries: 2024-07, 90d
        SRE development: 2024-10, 90d
        Assist with CKO Multi-Region Pre-requisites (1FTE): 2024-10, 180d
        Edge Gateway integration (1FTE): after egw1, 30d
        Client testing and migration to Multi-region (1 FTE): 30d
    section Core Payments
        Product and technical discoveries: 2024-8, 140d
        Development and testing: after cmsd2, 2025-1, 90d
    section Senior IC
        Product and technical discoveries: 2024-7, 180d
        Assist with Edge Gateway integration (0.5 FTE): after egw1, 14d
        Assist with client testing and migration to Multi-region (0.5 FTE): 28d
        Assist development/SRE work/CKO Multi-Region Pre-requisites (0.5 FTE): 2024-10, 180d
    section Edge Gateway
        Multi-Region setup: egw1, 2025-1, 90d