flowchart LR
    Client["Client Settlements Scheduler"]
    PTBClient["Pay To Bank Client"]
    EdgeGateway["Edge Gateway"]
    Gateway["Gateway"]
    Gatekeeper["Gatekeeper"]
    PayoutsEngine["Payouts Engine"]
    PaymentControls["Payment Controls"]
    Rails["Rails"]

    Client --> Gatekeeper
    PTBClient --> EdgeGateway
    EdgeGateway --> Gateway
    Gateway --> Gatekeeper
    Gatekeeper --> PayoutsEngine
    PayoutsEngine --> PaymentControls
    PaymentControls --> Rails
    Rails --> PaymentControls
